name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Generate Files
        run: pnpm build

      - name: Push Generated Files
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then
            echo "Generated files changed!"
            git commit -m "Update generated files"
            git push https://jacossaurus:${{ secrets.github_token }}@github.com/code-coogs-generated.git HEAD: main
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}

      - name: Send Build Failure Notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Build Failed!
            webhookUrl: ${{ secrets.WEBHOOK_URL }}