name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: bahmutov/npm-install@v1

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Generate Files
        run: npm run build

      - name: Push Generated Files
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then
            echo "Generated files changed!"
            git commit -m "Update generated files"
            git push https://jacossaurus:${{ secrets.github_token }}@github.com/code-coogs-generated.git HEAD: main
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}

      - name: Send Build Failure Notification
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Build Failed!
            webhookUrl: ${{ secrets.WEBHOOK_URL }}